### ISSUE TITLE
Error handling (crashed)

### ISSUE THREAD

**Issue by johnsickels** [jasonbyrne/minikin#2]
Foolish, I know.. but I spent a couple minutes debugging my app wondering why I was receiving this message when trying to run the server twice (it was already running in another terminal window):

```
{"level":50,"time":1598976779617,"pid":8066,"hostname":"XXXXXXXX","message":"Crashed"}
```

My proposal is a helpful error message like:

```
{"level":50,"time":1598976779617,"pid":8066,"hostname":"XXXXXXXX","message":"PORT 8001 is not available."}
```

Feel free to close if this undermines the simplicity of MINIKIN, but I wanted to drop this note here for myself to open a PR later.

**Comment by jasonbyrne** [comment]
This should be resolved in v1.0.23
